version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_service_db


  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile.Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      DOCKER_BUILDKIT: 1
    depends_on:
      - db


volumes:
  db:
    driver: local
